apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata: { name: auth-service-secrets, namespace: production }
spec:
  refreshInterval: 1h
  secretStoreRef: { name: aws-secretsmanager, kind: ClusterSecretStore }   # must match the kind in secretstore.yaml
  target: { name: auth-service-secrets, creationPolicy: Owner }
  data:
    - secretKey: JWT_SECRET
      remoteRef: { key: vaultflow/production/auth-service, property: JWT_SECRET }
    - secretKey: DB_PASSWORD
      remoteRef: { key: vaultflow/production/auth-service, property: DB_PASSWORD }
